config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  post 'favorites/:book_id/create' => 'favorites#create'
  post 'favorites/:book_id/destroy' => 'favorites#destroy'
  post 'book_comments/:book_id/create' => 'book_comments#create'
  post 'book_comments/:book_comment_id/destroy' => 'book_comments#destroy'
  post 'search' => 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :prefecture_code, :address_city, :address_street, :address_building

  has_many :books, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy


  attachment :profile_image

  include JpPrefecture
  jp_prefecture :prefecture_code

  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false}
  validates :introduction, length: {maximum: 50}
  validates :postal_code, presence: true
  validates :address, presence: true


  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)
    prefecture_name = resource.prefecture_name
    resource.address = "#{prefecture_name}#{resource.address_city}#{resource.address_street}#{resource.address_building}"
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        ThanksMailer.thanks_mail(resource).deliver_now
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   sign_up_params[:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.all

    @currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)

    @currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)
    #ここはもっといいやり方ありそう
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if !@isRoom
        @room = Room.new
        @entry = UserRoom.new
      end
    end
  end

  def edit
    if params[:id].to_i != current_user.id
      redirect_to user_path(current_user.id)
    else
      @user = User.find(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render "users/edit"
    end
  end

  def following
    user = User.find(params[:id])
    @users = user.following
    @headline = "Following Users"
    render 'show_follow'
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
    @headline = "Followers"
    render 'show_follow'
  end



  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<% if current_user.following?(user) %>
  <%= form_for(current_user.active_relationships.find_by(followed_id: user.id), method: :delete) do |f| %>
    <%= f.submit "フォロー外す", class: "btn btn-warning btn-block" %>
  <% end %>
<% else %>
  <%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, user.id %></div>
    <%= f.submit "フォローする", class: "btn btn-success btn-block"%>
  <% end %>
<% end %>

app/views/users/_template.erb
<div class="row">
	<div class="user_info">
		<h2>User info</h2>
		<%= attachment_image_tag user, :profile_image, size: '100x100', fallback: "/images/no-image.jpg" %>
		<table class="table">
			<tbody>
				<tr>
					<td>name</td>
					<td><%= user.name %></td>
				</tr>
				<tr>
					<td>introduction</td>
					<td><%= user.introduction %></td>
				</tr>
				<tr>
					<td>follows</td>
					<td>
						<a href="<%= following_user_path(user) %>">
							<%= user.following.count %>
						</a>
					</td>
				</tr>
				<tr>
					<td>followers</td>
					<td>
						<a href="<%= followers_user_path(user) %>">
							<%= user.followers.count %>
						</a>
					</td>
				</tr>
				<tr>
					<td ></td>
				</tr>
			</tbody>
		</table>
		<% if user.id == current_user.id %>
			<%= link_to edit_user_path(current_user.id) do %>
				<button type="button" class="btn btn-default btn-block" aria-label="Left Align"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
			<% end %>
		<% else %>
			<% if isRoom == true %>
				<%= link_to "チャットルームへ", room_path(roomId), class: "btn btn-block btn-default"%>
			<% else %>
				<%= form_for room do |f| %>
					<%= fields_for entry do |e| %>
						<%= e.hidden_field :user_id, value: user.id %>
					<% end %>
					<%= f.submit "チャットを始める", class: "btn btn-block btn-primary"%>
				<% end %>
			<% end %>
			<%= render 'users/follow_button', user: user%>
		<% end %>
	</div>
	<div class="new_book">
		<h2>New book</h2>
		<%= form_for(book, url: books_path) do |f| %>
			<label>Title</label><br>
			<%= f.text_field :title, style: "min-width: 100%;" %>
			<label>Opinion</label>
			<%= f.text_area :body, rows: "3", style: "min-width: 100%;" %><br>
			<%= f.submit "Create Book", class: "btn btn-block btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>User info</h2>
			<% if @user.errors.any? %>
				<div class="error_explanatation">
					<h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>

					<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li class="error_messages"><%= msg %></li>
					<% end %>
					</ul>
				</div>
			<% end %>
			<%= form_for(@user) do |f| %>
				<label>Name</label>
				<%= f.text_field :name, style: "min-width: 100%;" %><br>
				<label>Image</label>
				<%= f.attachment_field :profile_image %>
				<label>Introduction</label>
				<%= f.text_area :introduction, rows: "3", style: "min-width: 100%;" %><br>
				<%= f.submit "Update User", class: "btn btn-block btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/template', {user: @user, book: @book, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry} %>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: '50x50', fallback: "/images/no-image.jpg" %></td>
							<td><%= user.name %></td>
							<td>
								<a href="<%= following_user_path(user) %>">
									フォロー数：<%= user.following.count %>
								</a>
							</td>
							<td>
								<a href="<%= followers_user_path(user) %>">
									フォロワー数：<%= user.followers.count %>
								</a>
							</td>
							<td>
								<% if user != current_user %>
									<%= render 'users/follow_button', user: user%>
								<% end %>
							</td>
							<td><%= link_to "Show", user_path(user.id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<% if @book.errors.any? %>
				<div class="error_explanatation">
					<h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>

					<ul>
					<% @book.errors.full_messages.each do |msg| %>
						<li class="error_messages"><%= msg %></li>
					<% end %>
					</ul>
				</div>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/template', {user: @user, book: @book, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry} %>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td><%= attachment_image_tag book.user, :profile_image, size: '50x50', fallback: "/images/no-image.jpg" %></td>
						<td><%= link_to book.title, book_path(book.id) %></td>
						<td><%= book.body %></td>
						<td>コメント数： <%= book.book_comments.count %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div><br>
	<% if @user.id == current_user.id %>
	<div class="row">
		<div class="col-xs-12">
			<div id="gmap"></div>
			<script type="text/javascript">
				var map;
				var marker;
				var geocoder;
				function initMap() {
						geocoder = new google.maps.Geocoder();
						geocoder.geocode({
						'address': <%= "'#{@user.address}'".html_safe %>,
						'region': 'jp'
						}, function(results, status) {
							if (status === google.maps.GeocoderStatus.OK) {
							map = new google.maps.Map(document.getElementById('gmap'), {
								center: results[0].geometry.location,
								zoom: 17
						});
						marker = new google.maps.Marker({
						position: results[0].geometry.location,
						map: map
						});
						infoWindow = new google.maps.InfoWindow({
						content: '<h4>あなたの住所</h4>'
						});
						marker.addListener('click', function() {
							infoWindow.open(map, marker);
						});
						} else {
							alert(status);
						}
						});
					}
			</script>
			<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_API_KEY'] %>&callback=initMap" async defer></script>
		</div>
	</div>
	<% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:headline, @headline)%>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2><%= yield(:headline) %></h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: '50x50', fallback: "/images/no-image.jpg" %></td>
							<td><%= user.name %></td>
							<td>
								<a href="<%= following_user_path(user) %>">
									フォロー数：<%= user.following.count %>
								</a>
							</td>
							<td>
								<a href="<%= followers_user_path(user) %>">
									フォロワー数：<%= user.followers.count %>
								</a>
							</td>
							<td>
								<% if user != current_user %>
									<%= render 'users/follow_button', user: user%>
								<% end %>
							</td>
							<td><%= link_to "Show", user_path(user.id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/user_search_result.html.erb
<% provide(:condition, condition)%>
<% provide(:content, content)%>
<% provide(:search_method, search_method)%>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
      <h2>検索条件</h2>
      <p>
        <%= yield(:condition) %>：　
        <%= yield(:content) %> (<%= yield(:search_method) %>)
      </p>

      <h2>検索結果</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: '50x50', fallback: "/images/no-image.jpg" %></td>
							<td><%= user.name %></td>
							<td>
								<a href="<%= following_user_path(user) %>">
									フォロー数：<%= user.following.count %>
								</a>
							</td>
							<td>
								<a href="<%= followers_user_path(user) %>">
									フォロワー数：<%= user.followers.count %>
								</a>
							</td>
							<td>
								<% if user != current_user %>
									<%= render 'users/follow_button', user: user%>
								<% end %>
							</td>
							<td><%= link_to "Show", user_path(user.id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>