config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  post 'favorites/:book_id/create' => 'favorites#create'
  post 'favorites/:book_id/destroy' => 'favorites#destroy'
  post 'book_comments/:book_id/create' => 'book_comments#create'
  post 'book_comments/:book_comment_id/destroy' => 'book_comments#destroy'
  post 'search' => 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 199}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!

	def index
		@user = User.find(current_user.id)
    @book = Book.new
		@books = Book.all

		@currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)
	end

	def show
    @book = Book.find(params[:id])
		@user = User.find(@book.user_id)
		@book_new = Book.new
		@comments = BookComment.where(book_id: @book.id).order(:id)
		@comment = BookComment.new

		@currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "You have created book successfully."
			redirect_to book_path(@book.id)
		else
			@user = User.find(current_user.id)
			@books = Book.where(user_id: @user.id)
			render 'users/show'
		end
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "You have updated book successfully."
			redirect_to book_path(@book.id)
		else
			render 'books/edit'
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end


	private

	def book_params
		params.require(:book).permit(:title, :body, :user_id)
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_comments.html.erb
<%# コメントの一覧を表示(id昇順) %>
<table>
  <% comments.each do |comment| %>
    <tr>
      <td>
        <%= link_to comment.user do %>
          <%= attachment_image_tag comment.user, :profile_image, format: 'jpeg', size: '50x50' %><br>
          <%= comment.user.name %>
        <% end %>
      </td>
      <td><%= comment.comment %></td>
      <% if comment.user == current_user%>
        <td>
          <%= link_to "/book_comments/#{comment.id}/destroy", method: :post, "data-confirm" => "本当に消しますか？", remote: true do %>
            <button type="button" class="btn btn-danger btn-block" aria-label="Left Align">Destroy</button>
          <% end %>
        </td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/books/_book_index_row.html.erb
<tr>
  <td>
    <%= link_to user_path(book.user.id) do %>
      <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: '50x50', fallback: "/images/no-image.jpg" %>
    <% end %>
  </td>
  <td><%= link_to book.title, book_path(book.id) %></td>
  <td><%= book.body %></td>
  <td id="favorite-<%= book.id %>">
    <%= render 'books/favorite_button', book: book %>
  </td>
  <td>コメント数： <%= book.book_comments.count %></td>
</tr>

app/views/books/_book_show_row.html.erb
<tr>
  <td>
    <%= link_to user_path(user.id), user_id: user.id do %>
      <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: '50x50' %><br>
      <%= user.name %>
    <% end %>
  </td>
  <td><%= book.title %></td>
  <td><%= book.body %></td>
  <td id="favorite-<%= book.id %>">
    <%= render 'books/favorite_button', book: book %>
  </td>
  <td>コメント数： <%= book.book_comments.count %></td>
  <td></td>
  <% if user.id == current_user.id %>
    <td>
      <%= link_to edit_book_path(book.id) do %>
        <button type="button" class="btn btn-success btn-block" aria-label="Left Align">Edit</button>
      <% end %>
    </td>
    <td>
      <%= link_to book_path(book.id), method: :delete, "data-confirm" => "本当に消しますか？" do %>
        <button type="button" class="btn btn-danger btn-block" aria-label="Left Align">Destroy</button>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/books/_favorite_button.html.erb
<% if Favorite.find_by(user_id: current_user.id, book_id: book.id) %>
  <%= link_to "/favorites/#{book.id}/destroy", method: :post, remote: true do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> <%= book.favorites.count %>
  <% end%>
<% else %>
  <%= link_to "/favorites/#{book.id}/create", method: :post, remote: true do %>
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span> <%= book.favorites.count %>
  <% end %>
<% end %>

app/views/books/_form_book_comment.html.erb
<%= form_with(model: comment, url: "/book_comments/#{book.id}/create") do |f| %>
  <%= f.text_area :comment, rows: "3", style: "min-width: 100%;" %><br>
  <%= f.submit "送信", class: "btn btn-primary"%>
<% end %>

app/views/books/book_search_result.html.erb
<% provide(:condition, condition) %>
<% provide(:content, content) %>
<% provide(:search_method, search_method)%>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
      <h2>検索条件</h2>
      <p>
        <%= yield(:condition) %>：　
        <%= yield(:content) %> (<%= yield(:search_method) %>)
      </p>

      <h2>検索結果</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% books.each do |book| %>
						<tr>
							<td>
								<%= link_to user_path(book.user.id) do %>
									<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: '50x50', fallback: "/images/no-image.jpg" %>
								<% end %>
							</td>
							<td><%= link_to book.title, book_path(book.id) %></td>
							<td><%= book.body %></td>
							<td>
								<%= render 'books/favorite_button', book: book%>
							</td>
							<td>コメント数： <%= book.book_comments.count %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>Editing Book</h2>
			<% if @book.errors.any? %>
				<div class="error_explanatation">
					<h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3><br>

					<ul>
					<% @book.errors.full_messages.each do |msg| %>
						<li class="error_messages"><%= msg %></li>
					<% end %>
					</ul>
				</div>
			<% end %>
			<%= form_for(@book) do |f| %>
				<label for="inputTitle">Title</label>
				<%= f.text_field :title, style: "min-width: 100%;", id: "inputTitle" %><br>
				<label for="inputOpinion">Opinion</label>
				<%= f.text_area :body, rows: "3", style: "min-width: 100%;", id: "inputOpinion" %><br>
				<%= f.submit "Update Book", class: "btn btn-block btn-primary" %><br>
			<% end %>
				<P><%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %></P>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/template', {user: @user, book: @book, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry} %>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<%= render 'books/book_index_row', book: book %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/template', {user: @user, book: @book_new, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry} %>
		</div>
		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table">
				<tbody id="book-detail">
					<%= render 'books/book_show_row', { user: @user, book: @book} %>
				</tbody>
			</table>
			<div id="comment-index">
				<%= render 'books/book_comments', comments: @comments %>
			</div>
			<div id="comment-form">
				<%= render 'books/form_book_comment', comment: @comment, book: @book %>
			</div>
		</div>
	</div>
</div>